In [17]:
import pandas as pd

In [18]:
crop_yield=pd.read_csv("D:\\DEV\\crop-yield-pipeline\\backend\\data\\crop_yield.csv")

In [19]:
crop_yield.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [20]:
crop_yield.tail()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
19684,Small millets,1998,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [21]:
crop_yield.info()

<class 'pandas.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Crop             19689 non-null  str
 1   Crop_Year        19689 non-null  int64
 2   Season           19689 non-null  str
 3   State            19689 non-null  str
 4   Area             19689 non-null  float64
 5   Production       19689 non-null  int64
 6   Annual_Rainfall  19689 non-null  float64
 7   Fertilizer       19689 non-null  float64
 8   Pesticide        19689 non-null  float64
 9   Yield            19689 non-null  float64
dtypes: float64(5), int64(2), str(3)
memory usage: 1.5 MB

In [22]:
crop_yield.columns

Index(['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='str')

In [23]:
crop_yield.describe()

,Crop_Year,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
count,19689.000000,1.968900e+04,1.968900e+04,19689.000000,1.968900e+04,1.968900e+04,19689.000000
mean,2009.127584,1.799266e+05,1.643594e+07,1437.755177,2.410331e+07,4.884835e+04,79.954009
std,6.498099,7.328287e+05,2.630568e+08,816.909589,9.494600e+07,2.132874e+05,878.306193
min,1997.000000,5.000000e-01,0.000000e+00,301.300000,5.417000e+01,9.000000e-02,0.000000
25%,2004.000000,1.390000e+03,1.393000e+03,940.700000,1.880146e+05,3.567000e+02,0.600000
50%,2010.000000,9.317000e+03,1.380400e+04,1247.600000,1.234957e+06,2.421900e+03,1.030000
75%,2015.000000,7.511200e+04,1.227180e+05,1643.700000,1.000385e+07,2.004170e+04,2.388889
max,2020.000000,5.080810e+07,6.326000e+09,6552.700000,4.835407e+09,1.575051e+07,21105.000000

In [24]:
crop_yield.isnull().sum()

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [25]:
crop_yield["Crop"].unique()
crop_yield["Crop"].value_counts()

Crop
Rice                     1197
Maize                     975
Moong(Green Gram)         740
Urad                      733
Groundnut                 725
Sesamum                   685
Potato                    628
Sugarcane                 605
Wheat                     545
Rapeseed &Mustard         528
Bajra                     524
Jowar                     513
Arhar/Tur                 508
Ragi                      498
Gram                      490
Small millets             485
Cotton(lint)              476
Onion                     454
Sunflower                 441
Dry chillies              419
Other Kharif pulses       382
Horse-gram                371
Peas & beans (Pulses)     369
Tobacco                   364
Other  Rabi pulses        355
Soyabean                  349
Turmeric                  337
Masoor                    324
Ginger                    323
Linseed                   308
Castor seed               300
Barley                    297
Sweet potato              273
Garlic                    250
Banana                    245
Mesta                     210
Tapioca                   201
Coriander                 199
Niger seed                192
Jute                      181
Coconut                   172
Safflower                 169
Arecanut                  162
Sannhamp                  160
Other Cereals             146
Cashewnut                 134
Cowpea(Lobia)             134
Black pepper              126
other oilseeds            126
Moth                      110
Khesari                    75
Cardamom                   74
Guar seed                  63
Oilseeds total             29
Other Summer Pulses        10
Name: count, dtype: int64

In [26]:
crop_yield["State"].unique()
crop_yield["State"].value_counts()

State
Karnataka            1432
Andhra Pradesh       1266
West Bengal          1094
Chhattisgarh          915
Bihar                 896
Madhya Pradesh        845
Uttar Pradesh         825
Tamil Nadu            822
Gujarat               817
Maharashtra           770
Uttarakhand           764
Odisha                760
Assam                 731
Nagaland              689
Puducherry            670
Meghalaya             649
Haryana               631
Jammu and Kashmir     631
Himachal Pradesh      616
Kerala                534
Manipur               444
Tripura               441
Mizoram               416
Punjab                397
Telangana             397
Arunachal Pradesh     292
Jharkhand             270
Goa                   246
Sikkim                226
Delhi                 203
Name: count, dtype: int64

In [27]:
crop_yield["Yield"]==crop_yield["Production"]/crop_yield["Area"]

0        False
1        False
2        False
3        False
4        False
         ...
19684     True
19685     True
19686    False
19687    False
19688    False
Length: 19689, dtype: bool

In [28]:
print(crop_yield["Yield"].max())
print(crop_yield["Yield"].min())

21105.0
0.0

In [29]:
print(crop_yield["Crop_Year"].max())
print(crop_yield["Crop_Year"].min())

2020
1997

In [30]:
(crop_yield["Yield"]==0).sum()

np.int64(112)

In [31]:
print(crop_yield['Season'].value_counts())

Season
Kharif        8232
Rabi          5742
Whole Year    3717
Summer        1195
Autumn         414
Winter         389
Name: count, dtype: int64

In [32]:
print(crop_yield[crop_yield["Yield"] == crop_yield["Yield"].max()])

          Crop  Crop_Year      Season      State   Area  Production  \
13962  Coconut       2014  Whole Year  Telangana  439.0     9265095

       Annual_Rainfall  Fertilizer  Pesticide    Yield
13962            746.4    66271.44     144.87  21105.0

In [33]:
print(crop_yield.groupby("Crop")["Yield"].mean().sort_values(ascending=False).head(10))

Crop
Coconut         8652.000199
Sugarcane         51.727439
Banana            26.851128
Tapioca           16.667301
Potato            13.331718
Onion             13.247525
Sweet potato       9.240788
Jute               7.555393
Ginger             6.442202
Mesta              5.389204
Name: Yield, dtype: float64

In [42]:
crop_yield.drop(columns=["Area","Production"], inplace=True)

KeyError: "['Area', 'Production'] not found in axis"

In [43]:
crop_yield.columns.tolist()

['Crop',
 'Crop_Year',
 'Season',
 'State',
 'Annual_Rainfall',
 'Fertilizer',
 'Pesticide',
 'Yield']

In [4]:
crop_yield.to_csv("D:\\DEV\\crop-yield-pipeline\\backend\\data\\crop_yield_cleaned.csv",index=False)

NameError: name 'crop_yield' is not defined